
all:
	cd rumor; make; cd ..; cd demo1; make; cd ..; cd demo2; make; cd ..; cd demo3; make

clean:
	rm *~; cd demo1; make clean; cd ..; cd demo2; make clean; cd ..; cd demo3; make clean; cd ..; cd rumor; make clean

nice:
	rm *~

